### PR TITLE
Fix install space.

### PR DESCRIPTION
**Pull request by yvaind**
Attempt to fix install space for jenkins.

### CODE REVIEW

**Comment by yvaind** [comment]
@mbjelonic I am not sure whether this will actually fix the problem. Can I check somehow?

**Comment by mbjelonic** [comment]
Here is an example of loco:

`target_link_libraries(${PROJECT_NAME}
  ${catkin_LIBRARIES}
)

install(DIRECTORY include/${PROJECT_NAME}/
  DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
)

install(TARGETS ${PROJECT_NAME}
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)`

**Comment by mbjelonic** [comment]
I triggered a build of numopt on jenkins using this branch.

**Comment by yvaind** [comment]
Thanks for triggering the jenkins builds. Since it failed again, I incorporated the additional code from the loco example. Let's see if this fixes it...

**Comment by yvaind** [comment]
@mbjelonic You can start a new jenkins build.

**Comment by yvaind** [comment]
@dbellicoso Spotting that debug flag was excellent! In my case, the solver is now more than twice as fast! Thanks!!

**Comment by mbjelonic** [comment]
Nice! Good that it runs faster now! You should always be careful if you use open source projects from others. There might have as default the debug mode. 

It still does not compile on Jenkins. You can also test the install space by yourself by enabling it:

`catkin config --install`

**Comment by mbjelonic** [comment]
The install space, which is in the ìnstall/ folder of your catkin workspace, can make deployment of your compiled software much easier: You just need to copy the install folder to the new computer, source it and the software from this workspace is ready to be executed (of course you still need to install dependencies on packages/libraries which are not inside this workspace). What will be copied to the install space is specified at the end of the packages' CMakeLists.txt.

    The install space should at least have all libraries and executables of your package. So every target, which was added with add_library(myLibrary ...) or with add_executable(myExecutable ...) should be listed in the following statement:

    install(TARGETS myLibrary myExecutable
      ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
      LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
      RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
    )

    If you want to be able to write new code on the target machine which include header files of your package, you should also install the header files:

    install(DIRECTORY include/${PROJECT_NAME}/
      DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
    )

    If your package provides rosparam files, launchfiles and/or scripts (which should, according to the ros package standard, be located in param/ and launch/ subdirectories of your package), add the following:

    install(DIRECTORY param launch
      DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
    )

    If your package uses roscpp_nodewrap (or is a nodelet), do not forget to export the nodelet_plugins.xml file as well:

    install(FILES nodelet_plugins.xml
      DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
    )

    If your package uses contains scripts (shell, phyton), this is very important otherwise the +x (execute) permission will not be set:

    install(PROGRAMS
      bin/do_something.sh
      scripts/do_something.py
      DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
    )    

You must tell catkin to create the install space with the command catkin config --install. Disabling the install space can be done with the --no-install flag.

**Comment by yvaind** [comment]
This is very useful information, thank you!

**Comment by yvaind** [comment]
@mbjelonic Can you please trigger a new jenkins build? It finally works with my own install space.

**Comment by yvaind** [comment]
@mbjelonic I think you started a new jenkins build for numopt_osqp yesterday, right? Did you use this branch? Because unfortunately it failed again.

**Pull request merged**
